############
# Configs
############

configs:
  Staging Debug: debug
  Production Debug: debug
  Staging Release: release
  Production Release: release
  
targets:

  ############
  # Framework
  ############
  
  XAuthUIKit:
    name: XAuthUIKit
    type: framework
    platform: iOS

    settings:
      INFOPLIST_FILE: XAuthUIKit/Configs/Info.plist
      DEFINES_MODULE: YES

    # dependencies:
    #   # Internal Dependencies
    #   - target: XAuthKit
    #   - target: XAuthCommunicationsKit

    # dependencies:
      # - package: Kingfisher # nurirppan: tidak di pakai karna tidak ada thirdparty untuk UI
    
    sources:
      - path: Sources
        group: Modules/XAuthUIKit
      - path: Resources
        group: Modules/XAuthUIKit
      - path: Configs/Info.plist
        group: Modules/XAuthUIKit
      - path: Configs/xcconfig
        group: App/Configs

    configFiles:
      Staging Debug: Configs/xcconfig/Common.xcconfig
      Staging Release: Configs/xcconfig/Common.xcconfig
      Production Debug: Configs/xcconfig/Common.xcconfig
      Production Release: Configs/xcconfig/Common.xcconfig
  ############
  # Tests
  ############