# 
# Main file specification. 
# 
# In this file we will include:
# - Base min XcodeGen version configuration
# - Base iOS deploymentTarget
# - Name of our base Project
# - All the yaml files that we want to import when Xcodegen start parsing. 
#   The final yaml will include all the yml references from here.
# - ... other base options that could be useful


############
## Project 
name: XAuth


############
## Options
options:
  minimumXcodeGenVersion: 2.44.1
  generateEmptyDirectories: true


#############
## Settings

settings:
    IPHONEOS_DEPLOYMENT_TARGET: 16.0


############
## Imports

include:
  - packages.yml  
  - XAuthKit/config.yml
  - XAuthUIKit/config.yml
  - XAuthCommunicationsKit/config.yml  
  - App/config.yml # ini wajib di akhir karna modulenya dulu yang di genere baru root nya
  

