# ===================================================================
# 🆔 XAuthKit Module Configuration
# ===================================================================
# Modul ini bertanggung jawab atas core business logic, orkestrasi state,
# dan integrasi utama fitur otentikasi.
# Modul ini tidak mengurusi visual UI secara langsung.
# ===================================================================

targets:

  ############
  # Framework
  ############
  
  XAuthKit:
    name: XAuthKit
    # Menggunakan template dari project.yml untuk menghindari penulisan platform/type/script SwiftLint
    templates:
      - CommonFramework

    settings:
      base:
        # File info plist kustom khusus modul ini
        INFOPLIST_FILE: XAuthKit/Configs/Info.plist

    dependencies:
      # Modul internal pendukung yang dibutuhkan oleh modul ini
      - target: XAuthUIKit
      - target: XAuthCommunicationsKit
      - package: Factory
        product: FactoryKit
    
    sources:
      # Sumber berkas kode dan aset modul ini
      - path: Sources
        group: Modules/XAuthKit
      - path: Resources
        group: Modules/XAuthKit
      - path: Configs/Info.plist
        group: Modules/XAuthKit
      - path: Configs/xcconfig
        group: App/Configs

    # Menggunakan xcconfig file eksternal untuk konfigurasi flag build per skema
    configFiles:
      Staging Debug: Configs/xcconfig/Staging-Debug.xcconfig
      Staging Release: Configs/xcconfig/Staging-Release.xcconfig
      Production Debug: Configs/xcconfig/Production-Debug.xcconfig
      Production Release: Configs/xcconfig/Production-Release.xcconfig