############
# Configs
############

configs:
  Staging Debug: debug
  Production Debug: debug
  Staging Release: release
  Production Release: release
  
targets:

  ############
  # Framework
  ############
  
  XAuthKit:
    name: XAuthKit
    type: framework
    platform: iOS

    settings:
      DEFINES_MODULE: YES
      base:
        INFOPLIST_FILE: XAuthKit/Configs/Info.plist
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited)
        OTHER_SWIFT_FLAGS: $(inherited)

    # dependencies:
      # - package: Kingfisher # nurirppan: tidak di pakai karna tidak ada thirdparty untuk UI

    dependencies:
      # Internal Dependencies
      - target: XAuthUIKit
      - target: XAuthCommunicationsKit
    
    sources:
      - path: Sources
        group: Modules/XAuthKit
      - path: Resources
        group: Modules/XAuthKit
      - path: Configs/Info.plist
        group: Modules/XAuthKit
      - path: Configs/xcconfig
        group: App/Configs

    configFiles:
      Staging Debug: Configs/xcconfig/Staging-Debug.xcconfig
      Staging Release: Configs/xcconfig/Staging-Release.xcconfig
      Production Debug: Configs/xcconfig/Production-Debug.xcconfig
      Production Release: Configs/xcconfig/Production-Release.xcconfig
  ############
  # Tests
  ############