
############
# Configs
############

configs:
  Staging Debug: debug
  Production Debug: debug
  Staging Release: release
  Production Release: release


targets:

  ############
  # Application
  ############

  XAuth:
    type: application
    platform: iOS
    deploymentTarget: 16.0

    sources:
      - path: Sources
        group: App
      - path: Resources
        group: App
      - path: Configs/xcconfig
        group: App/Configs
      - path: Configs/entitlements
        group: App/Configs
      - path: Configs/google
        group: App/Configs
      - path: Configs/Info.plist
        group: App/Configs

    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/Colors.xcassets

    configFiles:
      Staging Debug: Configs/xcconfig/Staging-Debug.xcconfig
      Staging Release: Configs/xcconfig/Staging-Release.xcconfig
      Production Debug: Configs/xcconfig/Production-Debug.xcconfig
      Production Release: Configs/xcconfig/Production-Release.xcconfig

    settings:
      base:
        INFOPLIST_FILE: App/Configs/Info.plist
        OTHER_SWIFT_FLAGS: 
          - $(inherited)
            
    dependencies:
      # Internal Dependencies
      - target: XAuthKit
      - target: XAuthUIKit
      - target: XAuthCommunicationsKit

      # SPM dependencies
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics

    scheme:
      configVariants:
        - Staging
        - Production
      commandLineArguments:
        -FIRAnalyticsDebugEnabled: true
        # -FIRDebugDisabled: true


    