############
# Configs
############

configs:
  Staging Debug: debug
  Production Debug: debug
  Staging Release: release
  Production Release: release


targets:

  ############
  # Application
  ############

  XAuth:
    type: application
    platform: iOS
    deploymentTarget: 16.0

    sources:
      - path: Sources
        group: App
      - path: Resources
        group: App
      - path: Configs/xcconfig
        group: App/Configs
      - path: Configs/entitlements
        group: App/Configs
      - path: Configs/google
        group: App/Configs
      - path: Configs/Info.plist
        group: App/Configs

    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/Colors.xcassets

    configFiles:
      Staging Debug: Configs/xcconfig/Staging-Debug.xcconfig
      Staging Release: Configs/xcconfig/Staging-Release.xcconfig
      Production Debug: Configs/xcconfig/Production-Debug.xcconfig
      Production Release: Configs/xcconfig/Production-Release.xcconfig

    settings:
      base:
        INFOPLIST_FILE: App/Configs/Info.plist
        OTHER_SWIFT_FLAGS: 
          - $(inherited)
        
    dependencies:
      # Internal Dependencies
      - target: XAuthKit
      - target: XAuthUIKit
      - target: XAuthCommunicationsKit

      # SPM dependencies
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics

schemes:
  # 1. Scheme Staging Debug
  XAuth Staging Debug:
    build:
      targets:
        XAuth: all
    run:
      config: Staging Debug
      commandLineArguments:
        -FIRAnalyticsDebugEnabled: true
    test:
      config: Staging Debug
    profile:
      config: Staging Debug
    analyze:
      config: Staging Debug
    archive:
      config: Staging Debug

  # 2. Scheme Production Debug
  XAuth Production Debug:
    build:
      targets:
        XAuth: all
    run:
      config: Production Debug
      commandLineArguments:
        -FIRAnalyticsDebugEnabled: true
    test:
      config: Production Debug
    profile:
      config: Production Debug
    analyze:
      config: Production Debug
    archive:
      config: Production Debug

  # 3. Scheme Staging Release
  XAuth Staging Release:
    build:
      targets:
        XAuth: all
    run:
      config: Staging Release
    test:
      config: Staging Release
    profile:
      config: Staging Release
    analyze:
      config: Staging Release
    archive:
      config: Staging Release

  # 4. Scheme Production Release
  XAuth Production Release:
    build:
      targets:
        XAuth: all
    run:
      config: Production Release
    test:
      config: Production Release
    profile:
      config: Production Release
    analyze:
      config: Production Release
    archive:
      config: Production Release
    
