############
# Configs
############

configs:
  Staging Debug: debug
  Production Debug: debug
  Staging Release: release
  Production Release: release

targets:

  ############
  # Framework
  ############

  CommunicationsCore:
    name: CommunicationsCore
    type: framework
    platform: iOS

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "id.kompas.app.auth.communicationscore"
      INFOPLIST_FILE: CommunicationsCore/Configs/Info.plist

    scheme:
      gatherCovergageData: true
      testTargets:
        - name: CommunicationsCore_Tests
          parallelizable: true
          randomExecutionOrder: true

    # dependencies:
      # - package: Kingfisher
    
    sources:
      - path: Sources
        group: Modules/CommunicationsCore
      - path: Resources
        group: Modules/CommunicationsCore
      - path: Configs/Info.plist
        group: Modules/CommunicationsCore
      - path: Configs/xcconfig
        group: App/Configs

    configFiles:
      Staging Debug: Configs/xcconfig/Common.xcconfig
      Staging Release: Configs/xcconfig/Common.xcconfig
      Production Debug: Configs/xcconfig/Common.xcconfig
      Production Release: Configs/xcconfig/Common.xcconfig

  ############
  # Tests
  ############

  CommunicationsCore_Tests:
    name: CommunicationsCore_Tests
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: CommunicationsCore/Configs/Info-Test.plist
      PRODUCT_BUNDLE_IDENTIFIER: "id.kompas.app.auth.communicationscore.test"
      CODE_SIGN_STYLE: Manual

      base:
        MARKETING_VERSION: $(MYAPP_APP_VERSION)
        
    sources:
      - path: Tests
        group: Modules/CommunicationsCore
    dependencies:
      - target: CommunicationsCore

    scheme:
      testTargets:
        - CommunicationsCore_Tests
      gatherCoverageData: true