# ===================================================================
# 📡 XAuthCommunicationsKit Module Configuration
# ===================================================================
# Modul ini bertanggung jawab atas integrasi jaringan (API Call,
# HTTP networking, serialization data json, dan endpoints).
# Modul ini berdiri sendiri dan tidak memiliki UI atau dependensi bisnis.
# ===================================================================

targets:

  ############
  # Framework
  ############

  XAuthCommunicationsKit:
    name: XAuthCommunicationsKit
    # Menggunakan template dari project.yml untuk menghindari penulisan platform/type/script SwiftLint
    templates:
      - CommonFramework

    settings:
      base:
        # File info plist kustom khusus modul ini
        INFOPLIST_FILE: XAuthCommunicationsKit/Configs/Info.plist

    dependencies:
      - package: NetDataLibrary
        product: NetDataLibrary
      - package: Factory
        product: FactoryKit


    sources:
      # Sumber berkas kode dan aset modul ini
      - path: Sources
        group: Modules/XAuthCommunicationsKit
      - path: Resources
        group: Modules/XAuthCommunicationsKit
      - path: Configs/Info.plist
        group: Modules/XAuthCommunicationsKit
      - path: Configs/xcconfig
        group: App/Configs

    # Menggunakan xcconfig file eksternal untuk konfigurasi flag build per skema
    configFiles:
      Staging Debug: Configs/xcconfig/Staging-Debug.xcconfig
      Staging Release: Configs/xcconfig/Staging-Release.xcconfig
      Production Debug: Configs/xcconfig/Production-Debug.xcconfig
      Production Release: Configs/xcconfig/Production-Release.xcconfig

