# ===================================================================
# 📡 XAuthCommunicationsKit Module Configuration
# ===================================================================
# Modul ini bertanggung jawab atas integrasi jaringan (API Call,
# HTTP networking, serialization data json, dan endpoints).
# Modul ini berdiri sendiri dan tidak memiliki UI atau dependensi bisnis.
# ===================================================================

targets:

  ############
  # Framework
  ############

  XAuthCommunicationsKit:
    name: XAuthCommunicationsKit
    # Menggunakan template dari project.yml untuk menghindari penulisan platform/type/script SwiftLint
    templates:
      - CommonFramework

    settings:
      base:
        # File info plist kustom khusus modul ini
        INFOPLIST_FILE: XAuthCommunicationsKit/Configs/Info.plist

    dependencies:
      - package: NetDataLibrary
        product: NetDataLibrary
      - package: Factory
        product: FactoryKit

    # Pengaturan skema Xcode bawaan modul ini
    scheme:
      gatherCoverageData: true # Mengaktifkan report cakupan testing kode
      testTargets:
        - name: XAuthCommunicationsKit_Tests
          parallelizable: true     # Menjalankan test secara paralel demi kecepatan
          randomExecutionOrder: true # Mengacak urutan pengetesan untuk menguji kerapian state testing
    
    sources:
      # Sumber berkas kode dan aset modul ini
      - path: Sources
        group: Modules/XAuthCommunicationsKit
      - path: Resources
        group: Modules/XAuthCommunicationsKit
      - path: Configs/Info.plist
        group: Modules/XAuthCommunicationsKit
      - path: Configs/xcconfig
        group: App/Configs

    # Menggunakan xcconfig file eksternal untuk konfigurasi flag build per skema
    configFiles:
      Staging Debug: Configs/xcconfig/Staging-Debug.xcconfig
      Staging Release: Configs/xcconfig/Staging-Release.xcconfig
      Production Debug: Configs/xcconfig/Production-Debug.xcconfig
      Production Release: Configs/xcconfig/Production-Release.xcconfig

  ############
  # Tests Target
  ############

  XAuthCommunicationsKit_Tests:
    name: XAuthCommunicationsKit_Tests
    type: bundle.unit-test # Tipe modul berupa Unit Test Bundle
    platform: iOS
    settings:
      INFOPLIST_FILE: XAuthCommunicationsKit/Configs/Info-Test.plist
        
    sources:
      # Sumber berkas Unit Tests
      - path: Tests
        group: Modules/XAuthCommunicationsKit
    dependencies:
      # Unit test bergantung pada modul framework utama yang akan di-test
      - target: XAuthCommunicationsKit

    # Skema tersendiri untuk menjalankan test bundle ini
    scheme:
      testTargets:
        - XAuthCommunicationsKit_Tests
      gatherCoverageData: true
