############
# Configs 
############

configs:
  Staging Debug: debug
  Production Debug: debug
  Staging Release: release
  Production Release: release

targets:

  ############
  # Framework
  ############

  XAuthCommunicationsKit:
    name: XAuthCommunicationsKit
    type: framework
    platform: iOS

    settings:
      DEFINES_MODULE: YES
      base:
        INFOPLIST_FILE: XAuthCommunicationsKit/Configs/Info.plist
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited)
        OTHER_SWIFT_FLAGS: $(inherited)

    dependencies:
      - package: SwiftLint
        product: SwiftLintBuildToolPlugin
        kind: XcodeBuildToolPlugin
    #   # Internal Dependencies
    #   - target: XAuthKit
    #   - target: XAuthUIKit

    scheme:
      gatherCovergageData: true
      testTargets:
        - name: XAuthCommunicationsKit_Tests
          parallelizable: true
          randomExecutionOrder: true

    # dependencies:
      # - package: Kingfisher
    
    sources:
      - path: Sources
        group: Modules/XAuthCommunicationsKit
      - path: Resources
        group: Modules/XAuthCommunicationsKit
      - path: Configs/Info.plist
        group: Modules/XAuthCommunicationsKit
      - path: Configs/xcconfig
        group: App/Configs

    configFiles:
      Staging Debug: Configs/xcconfig/Staging-Debug.xcconfig
      Staging Release: Configs/xcconfig/Staging-Release.xcconfig
      Production Debug: Configs/xcconfig/Production-Debug.xcconfig
      Production Release: Configs/xcconfig/Production-Release.xcconfig

  ############
  # Tests
  ############

  XAuthCommunicationsKit_Tests:
    name: XAuthCommunicationsKit_Tests
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: XAuthCommunicationsKit/Configs/Info-Test.plist
        
    sources:
      - path: Tests
        group: Modules/XAuthCommunicationsKit
    dependencies:
      - target: XAuthCommunicationsKit

    scheme:
      testTargets:
        - XAuthCommunicationsKit_Tests
      gatherCoverageData: true
