############
# Configs
############

configs:
  Staging Debug: debug
  Production Debug: debug
  Staging Release: release
  Production Release: release
  
targets:

  ############
  # Framework
  ############
  
  UICore:
    name: UICore
    type: framework
    platform: iOS

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "id.kompas.app.auth.uicore"
      INFOPLIST_FILE: UICore/Configs/Info.plist

    base:
      MARKETING_VERSION: $(MYAPP_APP_VERSION)

    # dependencies:
      # - package: Kingfisher # nurirppan: tidak di pakai karna tidak ada thirdparty untuk UI
    
    sources:
      - path: Sources
        group: Modules/UICore
      - path: Resources
        group: Modules/UICore
      - path: Configs/Info.plist
        group: Modules/UICore
      - path: Configs/xcconfig
        group: App/Configs

    configFiles:
      Staging Debug: Configs/xcconfig/Common.xcconfig
      Staging Release: Configs/xcconfig/Common.xcconfig
      Production Debug: Configs/xcconfig/Common.xcconfig
      Production Release: Configs/xcconfig/Common.xcconfig
  ############
  # Tests
  ############